steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-central1-docker.pkg.dev/project-fd57960c-bd1d-4bf4-bf9/ats-ai/streamlit-app:latest', '-f', 'streamlit_app/Dockerfile', '.' ]
images:
- 'us-central1-docker.pkg.dev/project-fd57960c-bd1d-4bf4-bf9/ats-ai/streamlit-app:latest'
